### ISSUE TITLE
Error EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by vaughanwatson** [chrisallenlane/wit-cms#6]
On typing node app.js the following error occurs:

fs.js:603
var r = binding.read(fd, buffer, offset, length, position);

Error EISDIR: illegal operation on a directory, read
at Error (native)
at Object.fs.readsync (fs.js:603:19)
at Object.fs.readFileSync (fs.js:438:24)
at path-to-where-i-installed-witcms\app\boot\posts.js:50:23
at Array.forEach (native)
at path-to-where-i-installed-witcms\app\boot\posts.js:36:11
at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by chrisallenlane** [comment]
Hi, @vaughanwatson 

So, there could be a handful of problems here.

First thing to note is that `wit-cms` itself is a module that should be included into an Express app, rather than an application itself. With that said, you'll never need to "execute" `wit-cms` like you're trying to do here.

If you're looking for turnkey Express app built on wit, check out [wit-bootstrap].

Secondly, make sure that your dependencies are up-to-date, because I published a new `major` version of `wit-cms` recently.

Please give that a try and let me know the results. Thanks!

[wit-bootstrap]: https://github.com/chrisallenlane/wit-bootstrap

**Comment by vaughanwatson** [comment]
Hi @chrisallenlane 

The turnkey Express app built on wit ( wit-bootstrap ), Works like a dream!

I'm a happy bunny now. Thanks for the help.

**Comment by chrisallenlane** [comment]
Great to hear. Thanks!
