### ISSUE TITLE
Reloading .md files after edit

### ISSUE THREAD

**Issue by aevare** [chrisallenlane/wit-cms#8]
I like the simplicity of the cms so I have started on an editor for the .md files.

The problem I run into is after the file has been changed, the server has all the files cached.
Is there any way to refresh the pages/posts list without restarting the server?

**Comment by chrisallenlane** [comment]
There's nothing built-in to do that, because I'm trying to keep the codebase as simple as possible.

You could probably rig that up without too much work, though.

I use [pm2][] to manage deployments and restarts on my own website. Here's the relevant snippet from my [package.json][1] currently:

```javascript
// ...

  "scripts": {
    "deploy"  : "git fetch origin; git rebase origin/master; npm install; pm2 restart 'chris-allen-lane.com'",
    "show"    : "pm2 show 'chris-allen-lane.com'",
    "develop" : "pm2 start app --name='chris-allen-lane.com' --watch='app pages posts'",
    "logs"    : "pm2 logs 'chris-allen-lane.com'",
    "start"   : "pm2 start app --name='chris-allen-lane.com'",
    "stop"    : "pm2 stop 'chris-allen-lane.com'"
  },

// ...
```

If you hack around a bit, you could probably get `pm2` to `--watch` the markdown files, and restart when they are changed.

Actually (now that I take a closer look at that snippet), my own `develop` command might do that already. I never tried a hot-reload on the markdown files before :smile:

Anyway, think something like that might work for you?

[pm2]: https://www.npmjs.com/package/pm2
[1]: https://github.com/chrisallenlane/chris-allen-lane.com/blob/master/package.json
